# Generated by Django 4.0.1 on 2023-01-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=32, verbose_name='任务名称')),
                ('taskid', models.CharField(max_length=32, verbose_name='任务id')),
                ('description', models.CharField(max_length=100, verbose_name='任务描述')),
                ('global_iteration', models.IntegerField(verbose_name='全局迭代次数')),
                ('local_iteration', models.IntegerField(verbose_name='本地迭代次数')),
                ('algorithm', models.CharField(max_length=32, verbose_name='算法')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('status', models.IntegerField(verbose_name='任务状态')),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名称')),
                ('userid', models.CharField(max_length=32, verbose_name='用户id')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('uemail', models.EmailField(max_length=254, verbose_name='注册邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=32, verbose_name='用户id')),
                ('taskid', models.CharField(max_length=32, verbose_name='任务id')),
            ],
        ),
    ]
