# Generated by Django 4.0.1 on 2023-02-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='chose_num',
            field=models.IntegerField(default=5, verbose_name='每轮选择节点数'),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='client_num',
            field=models.IntegerField(default=10, verbose_name='使用节点数'),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='data_type',
            field=models.CharField(default='mnist', max_length=32, verbose_name='数据集类型'),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='deeplg_alg',
            field=models.CharField(default='default', max_length=32, verbose_name='深度学习算法'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='algorithm',
            field=models.CharField(max_length=32, verbose_name='联邦学习算法'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='description',
            field=models.TextField(verbose_name='数据集描述'),
        ),
    ]
