# Generated by Django 4.0.1 on 2023-02-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_taskinfo_chose_num_taskinfo_client_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
