# Generated by Django 4.0.1 on 2023-02-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_taskinfo_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=32, verbose_name='任务id')),
                ('data', models.TextField(verbose_name='数据accloss')),
            ],
        ),
    ]
