# Generated by Django 4.0.1 on 2023-02-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_taskdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='cvote',
            field=models.TextField(default=None, verbose_name='client_vote'),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='svote',
            field=models.TextField(default=None, verbose_name='server_vote'),
        ),
    ]
