# Generated by Django 4.0.1 on 2023-03-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_taskdata_cvote_taskdata_svote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='cvote',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='client_vote'),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='svote',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='server_vote'),
        ),
    ]
